server:
  port: 8030
  servlet:
    context-path: /consumer-b
spring:
  application:
    name: consumer-b
eureka:
  instance:
    instance-id: consumer-b-standalone
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8000/eureka-server/eureka/
    register-with-eureka: true #是否将应用实例注册到eureka server
    registry-fetch-interval-seconds: 2 #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    security:
      basic:
        user: admin
        password: ok

#开启GZIP压缩
feign:
  compression:
    request:
      # 开启请求压缩
      enabled: true
      # 配置压缩的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限，单位字节,默认2048
      min-request-size: 1
    response:
      # 开启响应压缩
      enabled: true
