spring:
  application:
    name: eureka-server
  security:
    basic:
      enable: true
    user:
      name: admin
      password: ok
  profiles:
    active: standalone
server:
  servlet:
    context-path: /eureka-server
